### ISSUE TITLE
Create own EntityAdapter and replace the original one

### ISSUE THREAD

**Issue by BigOHenry** [apitte/openapi#19]
Hello,
in documentation is 

> Entity is loaded by reflection, it loads all public properties using EntityAdapter. You can redefine entity adapter by interface.

**The problem is, i dont know how. I created new class:**
```
<?php declare(strict_types = 1);

namespace App\Controllers\Entity;

use Apitte\OpenApi\SchemaDefinition\Entity\IEntityAdapter;

/**
 * Class MyEntityAdapter
 * @package App\Controllers\Entity
 */
class MyEntityAdapter implements IEntityAdapter
{
    /**
     * @param mixed $object
     * @return mixed
     */
    public function getMetadata($object) {
        return ['test' => 1];
    }
}
```
**registred it config.neon**
	`- App\Controllers\Entity\MyEntityAdapter`

**and getting this error:**
![image](https://user-images.githubusercontent.com/15823552/61378486-c635de00-a8a5-11e9-9ead-0ea92807f8c0.png)

I dont know how to define MyEntityAdapter correctly. Is there any way?
 Thank you!

**Comment by mabar** [comment]
This should probably work.

```
services:
  api.openapi.entityDefinition:
    factory: MyEntityAdapter
    # or disable autowiring and register your service
    autowired: false 
```

**Comment by mabar** [comment]
Btw, what is the reason for this change?

**Comment by BigOHenry** [comment]
Thank you! I will try it. 
Reason is i dont use Doctrine Entities. I need to get metadata from my own objects (attributes are stored in database with datatypes, etc.)

**Comment by mabar** [comment]
Entity is probably not the best name. These "entities" are just data transfer objects for mapping between request, response and application data structures. It's not connected to doctrine in any way

**Comment by BigOHenry** [comment]
This works!
```
services:
  api.openapi.entityAdapter:
    factory: MyEntityAdapter
    # or disable autowiring and register your service
    autowired: false
```

Thank you!
